apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Chieme01/kubernetes-application-configuration
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: python

  syncPolicy:
    syncOptions:
    # Create namespace for deploying applications if namespace doesn't exist.
    - CreateNamespace=true
  
  # Automatically fetch changes to the repo
  automated:
  # Undo and override manual changes to the cluster
    selfHeal: true
  # Also delete cluster components that were deleted repo's code
    prune: true

