apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels: 
    app: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python-container
        image: devopscontainerregistry.azurecr.io/app:12d680be2ac6a6aad3711a7887d91af1e838bc40
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-secret
