apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels: 
    app: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python-container
        image: devopscontainerregistry.azurecr.io/app:99fd9411a34b22ec6a6b164385d0071a84660f5a
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-secret
